### ISSUE TITLE
Error when building Oreo

### ISSUE THREAD

**Issue by MightyM17** [Unlegacy-Android/android_device_samsung_espresso#1]
I am trying to build LineageOS oreo (there is no issues in that repo :( ) but i get this error
```
ninja: error: '/home/mighty/Los/out/target/product/espresso3g/obj/lib/libsrv_init.so.toc', needed by '/home/mighty/Los/out/target/product/espresso3g/obj/EXECUTABLES/pvrsrvinit_intermediates/LINKED/pvrsrvinit', missing and no known rule to make it
11:55:01 ninja failed with: exit status 1
```
I have hardware/ti and vendor/ti still

**Comment by andi34** [comment]
Sorry, I am not working on android devices anymore and can't assist you.

**Comment by andi34** [comment]
Maybe check our Gerrit, e.g. https://gerrit.unlegacy-android.org/q/topic:%22omap-o%22+(status:open%20OR%20status:merged)

**Comment by MightyM17** [comment]
> Sorry, I am not working on android devices anymore and can't assist you.

I remember someone had built LOS 15.1 for tab2 but u closed the thread :(

**Comment by MightyM17** [comment]
> Maybe check our Gerrit, e.g. https://gerrit.unlegacy-android.org/q/topic:%22omap-o%22+(status:open%20OR%20status:merged)

I cant seem to find a fix for it anywhere

**Comment by andi34** [comment]
> > Sorry, I am not working on android devices anymore and can't assist you.
> 
> I remember someone had built LOS 15.1 for tab2 but u closed the thread :(

Yes, I am asking to close threads if people use my work (e.g. compiled Roms) without permissions and that's my right. The source is open for everyone as you can see.
